### ISSUE TITLE
Introduce structure!

### ISSUE THREAD

**Issue by szepeviktor** [clubhouse/exporter#11]
Hello! What an anti-software we have here :)

Would you welcome few shell functions

- making the script readable
- and much-much-much smaller
- and more robust/less error prone?

@jeremyheiler What do you think?

**Comment by szepeviktor** [comment]
for example

```bash
api()
{
    local request="$1"
    local filename="${2:-$1}"

    curl -X GET \
      -H "Content-Type: application/json" \
      -L "https://api.clubhouse.io/api/v3/${request}?token=${CLUBHOUSE_API_TOKEN}" >"data/${filename}.json"
}
```

**Comment by jeremyheiler** [comment]
@szepeviktor You are free to fork the repository or make your own scripts! However, at this time we're fine with the simplicity of the script as it is. Thank you for your interest!

**Comment by szepeviktor** [comment]
Okay.
