### ISSUE TITLE
Format the output to be more readable

### ISSUE THREAD

**Issue by b-antczak** [clubhouse/exporter#9]
Hello!
Using this script, I've noticed that the output it produces is not formatted at all, which makes reading it very difficult.
I propose including an additional line for each endpoint that takes the output and formats it using python's `json.dump()`, or perhaps a flag can be created.

What do you think?

**Comment by jeremyheiler** [comment]
Hi @b-antczak. Would a tool like `jq` solve this for you?

**Comment by b-antczak** [comment]
Sure!
